[[block]]
block = "cpu"
format = " $icon $barchart "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(width:1) / $mem_total "

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
warning = 10
alert = 5

[[block]]
block = "disk_space"
path = "~"
info_type = "free"
warning = 10
alert = 5

[[block]]
block = "net"
format = " $icon {$ssid $ip|$ip} "

[[block]]
block = "sound"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(format:'%Y/%m/%d %R') "
interval = 60

[theme]
theme = "plain"

[icons]
icons = "awesome6"

[theme.overrides]
idle_bg = "#2d2d2d"
idle_fg = "#d3d0c8"
good_bg = "#99cc99"
good_fg = "#2d2d2d"
warning_bg = "#ffcc66"
warning_fg = "#2d2d2d"
critical_bg = "#f2777a"
critical_fg = "#2d2d2d"
info_bg = "#66cccc"
info_fg = "#2d2d2d"
separator_bg = "#2d2d2d"
separator_fg = "#d3d0c8"
